### ISSUE TITLE
Better Multisite flushing

### ISSUE THREAD

**Issue by relogical** [rhubarbgroup/redis-cache#161] opened 2020-05-19 21:00 UTC
On a WPMU install it would really be nice to see a menu item or button on each subsites' admin area so that each admin can flush cache as needed.

**Comment by tillkruss** [comment] 2020-05-19 21:01
Great idea, can you submit a PR?

**Comment by naxvog** [comment] 2020-05-20 07:27
As the `WP_CACHE_KEY_SALT` is a global option most likely defined in wp-config.php this would currently still flush the cache for all sites (even if the salt is not set).
We could change the cache key generation method the include the current site-ID using `get_current_network_id`

**Comment by lkraav** [comment] 2020-05-20 09:11
Duplicate of #64 #33 #83 maybe others as well https://github.com/tillkruss/redis-cache/issues?q=multisite

I seem to recall something about this selective subsite cache flushing being more complex than it appears, possibly discussed in some other object cache plugin issue tracker. There are many global things, if you flush them, you will potentially desync rest of your multisite. Maybe solvable by some group exclusion magic, but not sure if anyone has worked through this.

**Comment by tillkruss** [comment] 2020-05-29 16:45
We could support flushing of individual sites with a LUA script to cover the basic use case.

**Comment by tillkruss** [comment] 2020-06-06 19:47
Anybody up for a PR?

**Comment by tillkruss** [comment] 2020-07-16 20:54
Built into the Pro version. Feel free to submit a PR here @relogical.

**Closed by tillkruss** 2020-07-16 20:54 UTC
Labels: feature request, help wanted
