### ISSUE TITLE
wp cache flush breaks when using redis cluster on 2.5.3

### ISSUE THREAD

**Issue by Trisky** [rhubarbgroup/redis-cache#543] opened 2024-08-06 11:48 UTC
## Description
wp cache flush breaks when using redis cluster on 2.5.3 and predis

## Expected Behavior
cache cleared

## Actual Behavior

Flush fails

```bash
wp cache flush
Predis\NotSupportedException: The command 'INFO' is not allowed in replication mode. in /var/html/www/vendor/predis/predis/src/Replication/ReplicationStrategy.php:51
Stack trace:
#0 /var/html/www/vendor/predis/predis/src/Connection/Replication/SentinelReplication.php(547): Predis\Replication\ReplicationStrategy->isReadOperation(Object(Predis\Command\Redis\INFO))
#1 /var/html/www/vendor/predis/predis/src/Connection/Replication/SentinelReplication.php(581): Predis\Connection\Replication\SentinelReplication->getConnectionInternal(Object(Predis\Command\Redis\INFO))
#2 /var/html/www/vendor/predis/predis/src/Connection/Replication/SentinelReplication.php(713): Predis\Connection\Replication\SentinelReplication->getConnectionByCommand(Object(Predis\Command\Redis\INFO))
#3 /var/html/www/vendor/predis/predis/src/Connection/Replication/SentinelReplication.php(753): Predis\Connection\Replication\SentinelReplication->retryCommandOnFailure(Object(Predis\Command\Redis\INFO), 'executeCommand')
#4 /var/html/www/vendor/predis/predis/src/Client.php(381): Predis\Connection\Replication\SentinelReplication->executeCommand(Object(Predis\Command\Redis\INFO))
#5 /var/html/www/vendor/predis/predis/src/Client.php(336): Predis\Client->executeCommand(Object(Predis\Command\Redis\INFO))
#6 /var/html/www/web/app/object-cache.php(1153): Predis\Client->__call('info', Array)
#7 /var/html/www/web/app/object-cache.php(562): WP_Object_Cache->fetch_info()
#8 /var/html/www/web/app/object-cache.php(256): WP_Object_Cache->__construct(true)
#9 /var/html/www/web/wp/wp-includes/load.php(860): wp_cache_init()
#10 /var/html/www/web/wp/wp-settings.php(144): wp_start_object_cache()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1374): require('/var/html/www/w...')
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1293): WP_CLI\Runner->load_wordpress()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#16 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('phar:///usr/loc...')
#17 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#18 {main}
Error: The object cache could not be flushed.
```

## Steps to Reproduce

1. Enable cluster with `WP_REDIS_DISABLE_GROUP_FLUSH=true`
2. run `wp cache flush `
3. error

## Additional context

Problem is fixed as soon as I rollback to v2.5.2

## Environment

* Plugin version: 2.5.3
* PHP version: 8.2
* WordPress version: 6.5.5

**Comment by tillkruss** [comment] 2024-08-06 15:49
Can you try the develop branch which includes #541?

**Comment by erfan-ilyas** [comment] 2024-08-07 15:06
![image](https://github.com/user-attachments/assets/b5652ea2-acef-4533-9f8d-c1bb018797fc)

Got the same issue.

**Comment by tillkruss** [comment] 2024-08-07 21:07
@erfan-ilyas I just merged #544, does that resolve it for you?

**Comment by dustinrue** [comment] 2024-09-21 18:37
@tillkruss I am seeing that #544 seems to cause this:

```
Predis\ClientException: Command `GETMASTER` is not a registered Redis command. in /var/www/html/wordpress/wp-content/plugins/redis-cache/dependencies/predis/predis/src/Command/Factory.php:67
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/redis-cache/dependencies/predis/predis/src/Client.php(313): Predis\Command\Factory->create()
#1 /var/www/html/wordpress/wp-content/plugins/redis-cache/dependencies/predis/predis/src/Client.php(304): Predis\Client->createCommand()
#2 /var/www/html/wordpress/wp-content/object-cache.php(1151): Predis\Client->__call()
#3 /var/www/html/wordpress/wp-content/object-cache.php(562): WP_Object_Cache->fetch_info()
```

If I revert this change it appears to work fine and I do not get OPs original issue about the info command. I am using this configuration:

```
define( 'WP_REDIS_CLIENT', 'predis' );
define( 'WP_REDIS_SENTINEL', 'mymaster' );
define( 'WP_REDIS_SERVERS', ['tcp://redis:26379/?password=ZfY2jy4W7xwA3spcJhHRtQ'] );
define( 'WP_REDIS_PASSWORD', 'ZfY2jy4W7xwA3spcJhHRtQ' );
define( 'WP_REDIS_TIMEOUT', 1 );
define( 'WP_REDIS_READ_TIMEOUT', 1 );
define( 'WP_REDIS_DATABASE', 0 ); 
```

I am running Redis Sentinal in Kube using the bitnami/redis chart. I only need to spec a single sentinel because the Kube load balancer will always route me to a live sentinel which is replicated. I am running the develop branch as is with that commit backed out.

**Comment by tillkruss** [comment] 2024-09-23 16:48
@yatsukhnenko Can you take another look at this?

**Comment by neverlless** [comment] 2024-09-30 10:26
+1

**Closed** 2024-10-15 16:56 UTC
Labels: bug

**Comment by erfan-ilyas** [comment] 2024-12-21 10:03
WIth this version: 2.5.4

While it does fix the original issue of "The command 'INFO' is not allowed in replication mode."

I no longer get this error:

But now a new issue appeared.

Now all the read queries are going to the Master Sentinel server.

While in the version 2.5.1 all the read queries were spread out to all the available servers, That was the expected behaviors.


- WordPress in Auto Scaled Env right now with 3 servers: Version 2.5.4
![2 5 4](https://github.com/user-attachments/assets/b2fce1b2-5d52-47a4-9312-5d54f69a535f)

- WordPress in Auto Scaled Env right now with 3 servers: Version 2.5.1
![2 5 1](https://github.com/user-attachments/assets/8ef94ae9-3ad6-492a-83e9-e2160250c8e2)

With the current version 2.5.4 all the load goes to a single master server.

**Comment by tillkruss** [comment] 2024-12-21 19:08
@erfan-ilyas Feel free to open a PR with a fix for Sentinel. It's outside the scope I can provide support for.
